### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by edherm** [zduvall/GoodTrees#2]
Hello GoodTrees team!

I have reviewed your schema and wanted to leave you some comments. Please look these over, discuss them with your team, and feel free to ask me any questions that you may have.

## Tree Table
- [x] `avgDifficulty`, `avgFunFactor`, `avgViewFromTop`
    - [x] Because these values depend on every review connected to a `Tree`, these values will have to be updated and stored EVERY time someone leaves a review. This is not a good use of server time. Instead, when someone `router.get`s an individual `Tree`, you should `include` all of that tree's relevant review data. You can do this at the model level, in your router, or on the client side javascript (wherever makes the most sense to you).  If you store it, you are essentially storing the same information twice, which is not what you want.
## Review Table
- [x] Your `difficulty`, `funFactor`, and `viewFromTop` are all listed as `VARCHAR(20)`, but you want to be able to average them into integers. Should they be integers or is there other logic you plan to implement for averaging them?
## ForestConnection
- [x] For `climbStatus`, what values are you planning on putting here? I'm not sure what the difference is between `favStatus` and this column.

PS This theme is awesome.

**Comment by zduvall** [comment]
Great feedback @edherm! 

1. For the three `avg` variables on the Tree table, we were thinking we'd want to be able to display those scores on trees in detailed views and collection views. That could lead to a lot of database querying if we don't store and update them each time there's a new review... Is it better to store less and query more? Or query less and store more? We're trying to understand the tradeoff.
2. Good point! We changed those to `int` that can be 1 - 4, and then we'll interpret it as words on the front end.
3. `climbSstatus` is for people to mark if they have "climbed" a tree or "want to climb" a tree once it's in their `forest`, it will be stored as a boolean, (like bookshelf with "read" or "want to read".) `favStatus` on the other hand is for people to mark it as a favorite. Does that make sense?

Also, there are now associations and tables on the database schema wiki tab, maybe you can check if those look good. Thank you!
